osem-master/config/routes.rb
Osem::Application.routes.draw do

  if ENV['OSEM_ICHAIN_ENABLED'] == 'true'
    devise_for :users, controllers: { registrations: :registrations }
  else
    devise_for :users,
               controllers: {
                   registrations: :registrations, confirmations: :confirmations,
                   omniauth_callbacks: 'users/omniauth_callbacks' },
               path: 'accounts'
  end

  # Use letter_opener_web to open mails in browser (e.g. necessary for Vagrant)
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :users, except: [:new, :index, :create, :destroy]

  namespace :admin do
    resources :users
    resources :comments, only: [:index]
    resources :conference do
      resource :contact, except: [:index, :new, :create, :show, :destroy]
      resource :schedule, only: [:show, :update]
      get 'commercials/render_commercial' => 'commercials#render_commercial'
      resources :commercials, only: [:index, :create, :update, :destroy]
      get '/volunteers_list' => 'volunteers#show'
      get '/volunteers' => 'volunteers#index', as: 'volunteers_info'
      patch '/volunteers' => 'volunteers#update', as: 'volunteers_update'

      resources :registrations, except: [:create, :new] do
        member do
          patch :toggle_attendance

        end
      end

      # Singletons
      resource :splashpage
      resource :venue do
        get 'venue_commercial/render_commercial' => 'venue_commercials#render_commercial'
        resource :venue_commercial, only: [:create, :update, :destroy]
        resources :rooms, except: [:show]
      end
      resource :registration_period
      resource :program do
        resource :cfp
        resources :tracks
        resources :event_types
        resources :difficulty_levels
        resources :events do
          member do
            patch :toggle_attendance
            get :registrations
            post :comment
            patch :accept
            patch :confirm
            patch :cancel
            patch :reject
            patch :unconfirm
            patch :restart
            get :vote
          end
        end
      end

      resources :tickets
      resources :sponsors, except: [:show]
      resources :lodgings, except: [:show]
      resources :targets, except: [:show]
      resources :campaigns, except: [:show]
      resources :emails, only: [:show, :update, :index]
      resources :roles, except: [ :new, :create ] do
        member do
          post :toggle_user
        end
      end

      resources :sponsorship_levels, except: [:show] do
        member do
          patch :up
          patch :down
        end
      end

      resources :questions do
        collection do
          patch :update_conference
        end
      end
    end
  end

  resources :conference, only: [:index, :show] do
    resource :program, only: [] do
      resources :proposal, except: :destroy do
        get 'commercials/render_commercial' => 'commercials#render_commercial'
        resources :commercials, only: [:create, :update, :destroy]
        member do
          get :registrations
          patch '/withdraw' => 'proposal#withdraw'
          get :registrations
          patch '/confirm' => 'proposal#confirm'
          patch '/restart' => 'proposal#restart'
        end
      end
    end

    # TODO: change conference_registrations to singular resource
    resource :conference_registration, path: 'register'
    resources :tickets, only: [:index]
    resources :ticket_purchases, only: [:create, :destroy]
    resource :subscriptions, only: [:create, :destroy]

    member do
      get :schedule
      get :events
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :conferences, only: [ :index, :show ] do
        resources :rooms, only: :index
        resources :tracks, only: :index
        resources :speakers, only: :index
        resources :events, only: :index
      end
      resources :rooms, only: :index
      resources :tracks, only: :index
      resources :speakers, only: :index
      resources :events, only: :index
    end
  end

  get '/admin' => redirect('/admin/conference')

  root to: 'conference#index', via: [:get, :options]
end

osem-master/app/controllers/admin/conference_controller.rb
module Admin
  class ConferenceController < Admin::BaseController
    load_and_authorize_resource :conference, find_by: :short_title
    load_resource :program, through: :conference, singleton: true, except: :index
    load_resource :user, only: [:remove_user]

    def index
      # Redirect to new form if there is no conference
      if Conference.count == 0
        redirect_to new_admin_conference_path
        return
      end

      @total_user = User.count
      @new_user = User.where('created_at > ?', current_user.last_sign_in_at).count

      @total_reg = Registration.count
      @new_reg = Registration.where('created_at > ?', current_user.last_sign_in_at).count

      @total_submissions = Event.count
      @new_submissions = Event.where('created_at > ?', current_user.last_sign_in_at).count

      @active_conferences = Conference.get_active_conferences_for_dashboard # pending or the last two
      @deactive_conferences = Conference.
          get_conferences_without_active_for_dashboard(@active_conferences) # conferences without active
      @conferences = @active_conferences + @deactive_conferences

      @recent_users = User.limit(5).order(created_at: :desc)
      @recent_events = Event.limit(5).order(created_at: :desc)
      @recent_registrations = Registration.limit(5).order(created_at: :desc)

      @top_submitter = Conference.get_top_submitter

      @submissions = {}
      @cfp_weeks = [0]

      @registrations = {}
      @registration_weeks = [0]

      @conferences.each do |c|
        # Event submissions over time chart
        @submissions[c.short_title] = c.get_submissions_per_week
        @cfp_weeks.push(@submissions[c.short_title].length)

        # Conference registrations over time chart
        @registrations[c.short_title] = c.get_registrations_per_week
        @registration_weeks.push(@registrations[c.short_title].length)
      end

      @cfp_weeks = @cfp_weeks.max
      @submissions = normalize_array_length(@submissions, @cfp_weeks)
      @cfp_weeks = @cfp_weeks > 0 ? (1..@cfp_weeks).to_a : 1

      @registration_weeks = @registration_weeks.max
      @registrations = normalize_array_length(@registrations, @registration_weeks)
      @registration_weeks = @registration_weeks > 0 ? (1..@registration_weeks).to_a : 1

      @event_distribution = Conference.event_distribution
      @user_distribution = Conference.user_distribution
    end

    def new
      @conference = Conference.new
    end

    def create
      @conference = Conference.new(conference_params)

      if @conference.save
        # user that creates the conference becomes organizer of that conference
        current_user.add_role :organizer, @conference

        redirect_to admin_conference_path(id: @conference.short_title),
                    notice: 'Conference was successfully created.'
      else
        flash[:error] = 'Could not create conference. ' + @conference.errors.full_messages.to_sentence
        render action: 'new'
      end
    end

    def update
      @conference = Conference.find_by(short_title: params[:id])
      short_title = @conference.short_title
      @conference.assign_attributes(conference_params)
      send_mail_on_conf_update = @conference.notify_on_dates_changed?

      if @conference.update_attributes(conference_params)
        ConferenceDateUpdateMailJob.perform_later(@conference) if send_mail_on_conf_update
        redirect_to edit_admin_conference_path(id: @conference.short_title),
                    notice: 'Conference was successfully updated.'
      else
        redirect_to edit_admin_conference_path(id: short_title),
                    error: 'Updating conference failed. ' \
                    "#{@conference.errors.full_messages.join('. ')}."
      end
    end

    def show
      @program = @conference.program
      unless @conference.program
        @program = Program.new(conference_id: @conference.id)
      end

      # Overview and since last login information
      @total_reg = @conference.registrations.count
      @new_reg = @conference.registrations.where('created_at > ?', current_user.last_sign_in_at).count

      @total_submissions = @program.events.count
      @new_submissions = @program.events.
          where('created_at > ?', current_user.last_sign_in_at).count

      @program_length = @conference.current_program_hours
      @new_program_length = @conference.new_program_hours(current_user.last_sign_in_at)

      #  Step by step list
      @conference_progress = @conference.get_status

      # Line charts
      @registrations = {@conference.short_title => @conference.get_registrations_per_week}
      @registration_weeks = [0]
      @registration_weeks.push(@registrations[@conference.short_title].length)

      @registration_weeks = @registration_weeks.max
      @registrations = normalize_array_length(@registrations, @registration_weeks)
      @registration_weeks = @registration_weeks > 0 ? (1..@registration_weeks).to_a : 1

      @submissions = Conference.get_event_state_line_colors

      @submissions_data = {}
      @submissions_data = @conference.get_submissions_data
      @cfp_weeks = 0
      if @submissions_data['Weeks']
        @cfp_weeks = @submissions_data['Weeks']
        @submissions_data = @submissions_data.except('Weeks')
      end

      # Doughnut charts
      @event_type_distribution = @conference.event_type_distribution
      @event_type_distribution_confirmed = @conference.event_type_distribution(:confirmed)

      @difficulty_levels_distribution = @conference.difficulty_levels_distribution
      @difficulty_levels_distribution_confirmed = @conference.
          difficulty_levels_distribution(:confirmed)

      @tracks_distribution = @conference.tracks_distribution
      @tracks_distribution_confirmed = @conference.tracks_distribution(:confirmed)

      # Recent actions information
      @recent_events = @conference.program.events.limit(5).order(created_at: :desc)
      @recent_registrations = @conference.registrations.limit(5).order(created_at: :desc)

      @top_submitter = @conference.get_top_submitter

      # get targets
      @registration_targets = @conference.get_targets(Target.units[:registrations])
      @submission_targets = @conference.get_targets(Target.units[:submissions])
      @program_minutes_targets = @conference.get_targets(Target.units[:program_minutes])

      # get campaigns
      @campaigns = @conference.get_campaigns

      respond_to do |format|
        format.html
        format.json { render json: @conference.to_json }
      end
    end

    def edit
      @conferences = Conference.all
      @date_string = date_string(@conference.start_date, @conference.end_date)
      respond_to do |format|
        format.html
        format.json { render json: @conference.to_json }
      end
    end

    private

    def conference_params
      params.require(:conference).permit(:title, :short_title, :description, :timezone,
                                         :start_date, :end_date, :rooms_attributes, :tracks_attributes,
                                         :tickets_attributes, :event_types_attributes,
                                         :picture, :picture_cache, :questions_attributes,
                                         :question_ids, :answers_attributes, :answer_ids, :difficulty_levels_attributes,
                                         :use_vpositions, :use_vdays, :vdays_attributes,
                                         :vpositions_attributes, :use_volunteers, :color,
                                         :sponsorship_levels_attributes, :sponsors_attributes,
                                         :targets, :targets_attributes,
                                         :campaigns, :campaigns_attributes, :registration_limit)
    end
  end
end

osem-master/app/controllers/api/v1/conferences_controller.rb
module Api
  module V1
    class ConferencesController < Api::BaseController
      load_resource find_by: :short_title
      respond_to :json

      def index
        render json: @conferences, serializer: ConferencesArraySerializer
      end

      def show
        render json: [@conference], serializer: ConferencesArraySerializer
      end
    end
  end
end

osem-master/app/controllers/conference_controller.rb
class ConferenceController < ApplicationController
  protect_from_forgery with: :null_session
  before_filter :respond_to_options
  load_and_authorize_resource find_by: :short_title
  load_resource :program, through: :conference, singleton: true, except: :index

  def index
    @current = Conference.where('end_date >= ?', Date.current).reorder(start_date: :asc)
    @antiquated = @conferences - @current
  end

  def show; end

  def schedule
    @rooms = @conference.venue.rooms if @conference.venue
    unless @conference.program.events.scheduled.any?
      redirect_to events_conference_path(@conference.short_title)
    end

    @events = @conference.program.events
    @events_xml = @events.scheduled.order(start_time: :asc).group_by{ |event| event.start_time.to_date }
    @dates = @conference.start_date..@conference.end_date
    @step_minutes = EventType::LENGTH_STEP.minutes
    @conf_start = 9
    conf_end = 20
    @conf_period = conf_end - @conf_start

    # the schedule takes you to today if it is a date of the schedule
    @current_day = @conference.current_conference_day
    @day = @current_day.present? ? @current_day : @dates.first
    return unless @current_day
    # the schedule takes you to the current time if it is beetween the start and the end time.
    @hour_column = @conference.hours_from_start_time(@conf_start, conf_end)
  end

  def events
    @dates = @conference.start_date..@conference.end_date

    @scheduled_events = @conference.program.events.scheduled
    @unscheduled_events = @conference.program.events.unscheduled

    day = @conference.current_conference_day
    @tag = day.strftime('%Y-%m-%d') if day
  end

  private

  def respond_to_options
    respond_to do |format|
      format.html { head :ok }
    end if request.options?
  end
end

osem-master/app/views/conference/_carousel.html.haml
- intervals = number_columns * 60 / EventType::LENGTH_STEP + 1
- width = 85 / intervals
- carousel_number = (@conf_period / number_columns.to_f).ceil
.carousel.slide{ id: "carousel-#{ date }-#{ number_columns }", |
                     "data-ride" => "carousel", |
                     "data-wrap" => "false", |
                     "data-interval" => "false" }
  / Wrapper for slides
  .carousel-inner
    - start_time = DateTime.parse("#{date} #{@conf_start}:00")
    - (0..carousel_number-1).each do |number|
      %div{ class: "#{ carousel_item_class(number, carousel_number, number_columns, @hour_column)}" }
        %table.table.table-bordered.schedule-table#schedule
          %tr
            %th
            - td_start_time = start_time
            - (1..intervals).each do |i|
              %th.date
                = (td_start_time).strftime("%H:%M")
              - td_start_time += @step_minutes

          - start_room_time = start_time
          - @rooms.each do |room|
            - start_room_time = start_time
            - span = 1
            %tr
              %td.room{ style: "height: #{ td_height(@rooms) }px;" }
                .room.elipsis.break-words{ style: "-webkit-line-clamp: #{ room_lines(@rooms) }; height: #{ room_height(@rooms) }px;" }
                  = room.name
                - events = room.events{ |e| e.start_time >= start_time and e.start_time < (start_time + number_columns.hour)}
                - (1..intervals).each do |i|
                  - if span > 1
                    - span -= 1
                  - else
                    - event = events.find{|e| e.start_time <= start_room_time and e.end_time > start_room_time}

                    - if event && (event.state == 'canceled' || event.state == 'withdrawn') && !event.intersecting_events.confirmed.empty?
                      - replacement_event = event.intersecting_events.confirmed.first
                      - event = (replacement_event.start_time <= start_room_time && replacement_event.end_time > start_room_time) ? replacement_event : nil

                    - if event
                      / There is an event, calculate the span and show it
                      - event_span =  (event.end_time.to_i - start_room_time.to_i) / 60 / EventType::LENGTH_STEP
                      - span = ((event_span + i - 1 ) > intervals ? intervals  + 1 - i : event_span)
                      = render partial: 'schedule_item', locals: {event: event, span: span, width: width}
                    - else
                      / if span equals 1 show an empty td
                      %td.no-padding{ width: "#{ width }%"}
                  - start_room_time += @step_minutes
          - start_time = start_room_time - @step_minutes

  / Controls
  %a.left.carousel-control{ href: "#carousel-#{ date }-#{ number_columns }", |
                            role: "button", |
                            "data-slide" => "prev" }
    %span.glyphicon.glyphicon-chevron-left
  %a.right.carousel-control{ href: "#carousel-#{ date }-#{ number_columns }", |
                             role: "button", |
                             "data-slide" => "next" }
    %span.glyphicon.glyphicon-chevron-right

osem-master/app/views/conference/_conference_details.html.haml
.row
  .col-md-12
    .well
      .row
        .col-md-4.text-center
          = image_tag(conference.picture_url, class: 'img-responsive') if conference.picture?
        .col-md-6
          %h3
            = conference.title
            %small
              %b
              = date_string(conference.start_date, conference.end_date)
          - if conference.venue
            %p
              = "#{conference.venue.city}/#{conference.venue.country_name}"
          - if !conference.description.blank?
            %p
              = markdown(conference.description)
        .col-md-2
          .btn-group-vertical
            - if !@conference || @conference != conference
              - if conference.splashpage && conference.splashpage.public
                = link_to "View Cycle Day", conference_path(conference.short_title), :class =>"btn btn-default"
            - if conference.program and conference.program.schedule_public
              = link_to "Schedule", schedule_conference_path(conference.short_title), :class =>"btn btn-default"
            - if conference.registration_open?
              - if conference.user_registered?(current_user)
                = link_to "My Registration", conference_conference_registration_path(conference.short_title), :class =>"btn btn-default"
              - else
                = link_to "Register", new_conference_conference_registration_path(conference.short_title), class: "btn btn-default", disabled: conference.registration_limit_exceeded?
                - if conference.registration_limit_exceeded?
                  Sorry, no places left
            - if !current_user.nil? && current_user.proposal_count(conference) > 0
              = link_to "My Proposals", conference_program_proposal_index_path(conference.short_title), :class =>"btn btn-default"
            - elsif can? :new, conference.program.events.new
              = link_to "Submit Proposal", new_conference_program_proposal_path(conference.short_title), :class =>"btn btn-default"
            - if current_user.nil? || !current_user.subscribed?(conference)
              = link_to 'Subscribe', conference_subscriptions_path(conference.short_title), method: :post, class: 'btn btn-default'
            - else
              = link_to 'Unsubscribe', conference_subscriptions_path(conference.short_title), method: :delete, class: 'btn btn-default'

osem-master/app/views/conference/_event.html.haml
%a.unstyled-link{href: url_for(conference_program_proposal_path(@conference.short_title, event.id))}
  .panel.panel-default
    .panel-body
      - if speaker = event.speakers.first
        = image_tag speaker.gravatar_url, :class => "img-circle pull-right all-speaker-pic", |
                                          :alt => speaker.name, |
                                          :title => speaker.name |
      %span.h3
        = event.title
        %br
        %small
          = event.subtitle
      %h4
        presented by #{event.speaker_names}
      %p
        = truncate(event.abstract, :length => 400)
        = link_to 'more', conference_program_proposal_path(@conference.short_title, event.id) if event.abstract.length > 400
      - if event.scheduled?
        %span.track
          %span.fa.fa-clock-o
          %span.label{ style: "background-color: grey" }
            = event.start_time.strftime('%H:%M')
            \-
            = event.end_time.strftime('%H:%M')
        %span.track
          %span.fa.fa-map-marker
          %span.label{ style: "background-color: grey" }
            = event.room.name
      - if event.track
        %span.track
          %span.fa.fa-road
          %span.label{ style: "background-color: #{event.track.color}; color: #{ contrast_color(event.track.color) }" }
            = event.track.name

osem-master/app/views/conference/_footer.html.haml
.scroll-top-wrapper
  = link_to "#banner", class: "smoothscroll" do
    %i.fa.fa-2x.fa-arrow-circle-up

:javascript
  $(function(){
    $(document).on( 'scroll', function(){
      if ($(window).scrollTop() > 100) {
          $('.scroll-top-wrapper').addClass('show');
      } else {
          $('.scroll-top-wrapper').removeClass('show');
      }
    });
  });

osem-master/app/views/conference/_gallery.html.haml
<!-- Modal -->
%div{ class: "modal fade", id: "gallery", tabindex: "-1", role: "dialog", "aria-labelledby" => "myLargeModalLabel", "aria-hidden"=> "true" }
  %div{ class: "modal-dialog modal-lg" }
    %div{ class: "modal-content" }
      %div{ class: "modal-body" }
        %div{ id: "carousel-example-generic", class: "carousel slide", "data-ride" => "carousel" }
          <!-- Wrapper for slides -->
          %div{ class: "carousel-inner" }

          <!-- Controls -->
          %a{ class: "left carousel-control", href: "#carousel-example-generic", role: "button", "data-slide" => "prev" }
            %span.fa.fa-chevron-left
          %a{ class: "right carousel-control", href: "#carousel-example-generic", role: "button", "data-slide" => "next" }
            %span.fa.fa-chevron-right


:javascript
  $(document).ready(function(){
    var count = 0;
    $('#gallery-btn').click(function(){
      if(count == 0){
        $('#gallery').modal('show');
        $('#gallery .modal-body').append('<i class="fa fa-spinner fa-spin fa-4x"></i>');
        count +=1;
      }
      else{
        $('#gallery').modal('show');
        return false;
      }
    });
  });

osem-master/app/views/conference/_lodging.html.haml
.container
  .row
    .col-md-12.text-center
      %h2
        Where to stay
        - if @conference.venue
          in
          = @conference.venue.city
      %p.lead
        We recommend these affordable lodging accommodations for your visit.
  - @conference.lodgings.each_slice(3) do |slice|
    .row.row-centered
      - slice.each do |lodging|
        .col-md-4.col-sm-4.ticket.col-centered.col-top
          .thumbnail
            - if !lodging.picture?
              %p.text-center
                %i.fa.fa-home.fa-5x
            - else
              -if lodging.website_link.present?
                = link_to(lodging.website_link, class: 'thumbnail') do
                  = image_tag lodging.picture.large.url, class: 'img-responsive img-lodging'
              - else
                = image_tag lodging.picture.large.url, class: 'img-responsive img-lodging'
            .caption
              %h3.text-center
                = lodging.name
              -if lodging.description.present?
                = markdown(lodging.description)

osem-master/app/views/conference/_program.html.haml
= content_for :splash_nav do
  %li
    %a.smoothscroll{ href: '#callforpapers' } Call For Papers

.container
  .row
    .col-md-12.text-center
      %h2
        Call for Papers
      %p.lead
        We are ready to accept your proposals for sessions!
  .row
    .col-md-6.col-md-offset-3.col-sm-10.col-sm-offset-1
      %p
        - if @conference.program.event_types.any?
          You can submit proposals for
          = "#{event_types(@conference)}."
        - if @conference.tracks.any?
          Proposals should fit in one of the
          = "#{pluralize(@conference.tracks.count, 'track')}:"
          = "#{tracks(@conference)}."
        The submission period has begun
        %em
          = @program.cfp.start_date.strftime('%A, %B %-d. %Y')
        and closes
        %em
          = @program.cfp.end_date.strftime('%A, %B %-d. %Y.')
        - if @conference.cfp_open?
          That means you have only
          %b= pluralize(@program.cfp.remaining_days, 'day')
          left!
          Remember
          = @conference.short_title
          will only be as good as the sessions you present. Submit early, submit often!
        - else
          The submission period is closed.
  .row
    .col-md-12.text-center
      %p.cta-button
        = link_to "Submit your paper now", conference_proposal_index_path(@conference.short_title), class: 'btn btn-success btn-lg text-center'

osem-master/app/views/conference/_registration.html.haml
= content_for :splash_nav do
  %li
    %a.smoothscroll{ href: '#registration' } Registration

.container
  .row
    .col-md-12.text-center
      %h1 Registration

      - if @conference.registration_limit_exceeded?
        %p
          Sorry, the conference registration limit has exceeded
      - else
        - if @conference.tickets.empty?
          %p.lead
            Going to
            = @conference.short_title
            is free of charge.
          %p
            We only ask you to register yourself until
            = @conference.registration_period.end_date.strftime('%A, %B %-d. %Y')
            so we can plan for the right amount of people.
            %p.cta-button
        - else
          %p
            The registration period ends on
            = @conference.registration_period.end_date.strftime('%A, %B %-d. %Y')
          %p.cta-button
        = link_to(new_conference_conference_registration_path(@conference.short_title), class: 'btn btn-lg btn-success') do
          Register Now

osem-master/app/views/conference/_schedule_item.html.haml
%td.event{ width: "#{ width * span }%" , |
           colspan: span, |
           role: "button" }
  %a.unstyled-link{href: url_for(conference_program_proposal_path(@conference.short_title, event.id))}
    %div{ class: "elipsis break-words event-title", |
          style: "-webkit-line-clamp: #{ event_lines(@rooms) }; height: #{ event_height(@rooms) }px;"} |

      - if event.state == 'canceled' || event.state == 'withdrawn'
        %span.label.label-danger.schedule-label CANCELED
      - elsif event.state == 'confirmed' && (!event.intersecting_events.canceled.empty? || !event.intersecting_events.withdrawn.empty?)
        %span.label.label-info.schedule-label REPLACEMENT

      = event.title

    - if speaker = event.speakers.first
      = image_tag speaker.gravatar_url, :class => "img-circle pull-right speaker-pic", |
                                        :alt => speaker.name, |
                                        :title => speaker.name, |
                                        :style => "height: #{ speaker_height(@rooms) }px; width: #{ speaker_width(@rooms) }px;"

osem-master/app/views/conference/_schedule_tabs.html.haml
%div{ role: "tabpanel" }
  / Nav tabs
  %ul.nav.nav-tabs{ role: "tablist" }
    %li{ class: "schedule #{ 'active' if active == 'schedule' }", role: "presentation" }
      = link_to('Schedule', schedule_conference_path(@conference.short_title))
    %li{ class: "program #{ 'active' if active == 'program' }", role: "presentation" }
      = link_to('All events', events_conference_path(@conference.short_title))

osem-master/app/views/conference/_social_media.html.haml
.container
  .row
    .col-md-12.text-center
      - unless @conference.contact.facebook.blank?
        = link_to "#{ @conference.contact.facebook }" do
          %i.fa.fa-facebook-square.fa-4x
      - unless @conference.contact.twitter.blank?
        = link_to "#{ @conference.contact.twitter }" do
          %i.fa.fa-twitter.fa-4x
      - unless @conference.contact.instagram.blank?
        = link_to "#{ @conference.contact.instagram }" do
          %i.fa.fa-instagram.fa-4x
      - unless @conference.contact.googleplus.blank?
        = link_to "#{ @conference.contact.googleplus }" do
          %i.fa.fa-google-plus-square.fa-4x
      - unless @conference.contact.email.blank?
        = mail_to "#{ @conference.contact.email }" do
          %i.fa.fa-envelope-o.fa-4x

osem-master/app/views/conference/events.html.haml
.container#program
  -if @scheduled_events.any?
    = render partial: 'schedule_tabs',  locals: { active: 'program' }

  %h1.text-center
    Program for
    = @conference.title
  .dropdown.program-dropdown
    %button{ type: "button", class: "btn btn-default dropdown-toggle", 'data-toggle' => "dropdown" }
      Dates
      %span.caret
    %ul.dropdown-menu
      - @dates.each do |date|
        %li.li-dropdown-program
          = link_to date, "##{date}", class: "program-selector#{ ' no-events-day' unless @conference.program.any_event_for_this_date?(date) }"
      - if @unscheduled_events.any?
        %li.li-dropdown-program
          = link_to('Unscheduled', "#unscheduled", class: 'program-selector')

  .row

    / scheduled events
    - date = nil
    - time = nil
    - @scheduled_events.each do |event|
      - unless event.start_time.strftime('%Y-%m-%d').eql?(date)
        .col-xs-12.col-md-12
          .date-content
            %span{ class: 'date-title', id: "#{ event.start_time.strftime('%Y-%m-%d') }" }
              = date = event.start_time.strftime('%Y-%m-%d')
            %a{ title: "Go up", class: "pull-right", href: "#program" }
              %i{ class: "fa fa-angle-double-up fa-lg", 'aria-hidden' => true }
      - unless event.start_time.strftime('%H:%M').eql?(time)
        .col-xs-12.col-md-1
          .start-time
            = time = event.start_time.strftime('%H:%M')
        .col-xs-12.col-md-11
          .new-time-event
            = render partial: 'event', locals: {event: event}
      - else
        .col-xs-12.col-md-11.col-md-offset-1
          = render partial: 'event', locals: {event: event}

    / confirmed events that are not scheduled
    - if @unscheduled_events.any?
      .col-xs-12.col-md-12
        .date-content
          %span.date-title#unscheduled
            Unscheduled events
          %a{ title: "Go up", class: "pull-right", href: "#program" }
            %i{ class: "fa fa-angle-double-up fa-lg", 'aria-hidden' => true }
      - @unscheduled_events.each do |event|
        .col-xs-12.col-md-12
          .unscheduled-event
            = render partial: 'event', locals: {event: event}

:javascript
  $('.program-selector').on('click', function(e) {
    $('.li-dropdown-program').removeClass('active');
  });

  // Go to current date and time
  $(document).ready(function(){
    document.getElementById("#{ @tag }").scrollIntoView();
  });