osem-master/config/routes.rb
Osem::Application.routes.draw do

  if ENV['OSEM_ICHAIN_ENABLED'] == 'true'
    devise_for :users, controllers: { registrations: :registrations }
  else
    devise_for :users,
               controllers: {
                   registrations: :registrations, confirmations: :confirmations,
                   omniauth_callbacks: 'users/omniauth_callbacks' },
               path: 'accounts'
  end

  # Use letter_opener_web to open mails in browser (e.g. necessary for Vagrant)
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :users, except: [:new, :index, :create, :destroy]

  namespace :admin do
    resources :users
    resources :comments, only: [:index]
    resources :conference do
      resource :contact, except: [:index, :new, :create, :show, :destroy]
      resource :schedule, only: [:show, :update]
      get 'commercials/render_commercial' => 'commercials#render_commercial'
      resources :commercials, only: [:index, :create, :update, :destroy]
      get '/volunteers_list' => 'volunteers#show'
      get '/volunteers' => 'volunteers#index', as: 'volunteers_info'
      patch '/volunteers' => 'volunteers#update', as: 'volunteers_update'

      resources :registrations, except: [:create, :new] do
        member do
          patch :toggle_attendance

        end
      end

      # Singletons
      resource :splashpage
      resource :venue do
        get 'venue_commercial/render_commercial' => 'venue_commercials#render_commercial'
        resource :venue_commercial, only: [:create, :update, :destroy]
        resources :rooms, except: [:show]
      end
      resource :registration_period
      resource :program do
        resource :cfp
        resources :tracks
        resources :event_types
        resources :difficulty_levels
        resources :events do
          member do
            patch :toggle_attendance
            get :registrations
            post :comment
            patch :accept
            patch :confirm
            patch :cancel
            patch :reject
            patch :unconfirm
            patch :restart
            get :vote
          end
        end
      end

      resources :tickets
      resources :sponsors, except: [:show]
      resources :lodgings, except: [:show]
      resources :targets, except: [:show]
      resources :campaigns, except: [:show]
      resources :emails, only: [:show, :update, :index]
      resources :roles, except: [ :new, :create ] do
        member do
          post :toggle_user
        end
      end

      resources :sponsorship_levels, except: [:show] do
        member do
          patch :up
          patch :down
        end
      end

      resources :questions do
        collection do
          patch :update_conference
        end
      end
    end
  end

  resources :conference, only: [:index, :show] do
    resource :program, only: [] do
      resources :proposal, except: :destroy do
        get 'commercials/render_commercial' => 'commercials#render_commercial'
        resources :commercials, only: [:create, :update, :destroy]
        member do
          get :registrations
          patch '/withdraw' => 'proposal#withdraw'
          get :registrations
          patch '/confirm' => 'proposal#confirm'
          patch '/restart' => 'proposal#restart'
        end
      end
    end

    # TODO: change conference_registrations to singular resource
    resource :conference_registration, path: 'register'
    resources :tickets, only: [:index]
    resources :ticket_purchases, only: [:create, :destroy]
    resource :subscriptions, only: [:create, :destroy]

    member do
      get :schedule
      get :events
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :conferences, only: [ :index, :show ] do
        resources :rooms, only: :index
        resources :tracks, only: :index
        resources :speakers, only: :index
        resources :events, only: :index
      end
      resources :rooms, only: :index
      resources :tracks, only: :index
      resources :speakers, only: :index
      resources :events, only: :index
    end
  end

  get '/admin' => redirect('/admin/conference')

  root to: 'conference#index', via: [:get, :options]
end

osem-master/app/models/user.rb
class IChainRecordNotFound < StandardError
end

class UserDisabled < StandardError
end

class User < ActiveRecord::Base
  rolify
  include Gravtastic
  gravtastic size: 32

  before_create :setup_role

  # add scope
  scope :comment_notifiable, ->(conference) {joins(:roles).where('roles.name IN (?)', [:organizer, :cfp]).where('roles.resource_type = ? AND roles.resource_id = ?', 'Conference', conference.id)}

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise_modules = []

  if ENV['OSEM_ICHAIN_ENABLED'] == 'true'
    devise_modules += [ :ichain_authenticatable, :ichain_registerable, :omniauthable, omniauth_providers: [] ]
  else
    devise_modules += [:database_authenticatable, :registerable,
                       :recoverable, :rememberable, :trackable, :validatable, :confirmable,
                       :omniauthable, omniauth_providers: [:suse, :google, :facebook, :github] ]
  end

  devise(*devise_modules)

  has_many :openids

  attr_accessor :login

  has_many :event_users, dependent: :destroy
  has_many :events, -> { uniq }, through: :event_users
  has_many :registrations, dependent: :destroy
  has_many :events_registrations, through: :registrations
  has_many :ticket_purchases, dependent: :destroy
  has_many :tickets, through: :ticket_purchases, source: :ticket
  has_many :votes, dependent: :destroy
  has_many :voted_events, through: :votes, source: :events
  has_many :subscriptions, dependent: :destroy
  accepts_nested_attributes_for :roles

  scope :admin, -> { where(is_admin: true) }

  validates :email, presence: true

  validates :username,
            uniqueness: {
                case_sensitive: false
            },
            presence: true

  validate :biography_limit

  ##
  # Checkes if the user attended the event
  # This is used for events that require registration
  # The user must have registered to attend the event
  # Gets an event
  # === Returns
  # * +true+ if the user attended the event
  # * +false+ if the user did not attend the event
  def attended_event? event
    event_registration = event.events_registrations.find_by(registration: self.registrations)

    return false unless event_registration.present?
    event_registration.attended
  end

  def name
    self[:name] || username
  end

  ##
  # Checks if a user has registered to an event
  # ====Returns
  # * +true+ or +false+
  def registered_to_event? event
    event.registrations.pluck(:id).include? self.registrations.find_by(conference_id: event.program.conference.id).id
  end

  def subscribed? conference
    self.subscriptions.find_by(conference_id: conference.id).present?
  end

  def supports? conference
    ticket_purchases.find_by(conference_id: conference.id).present?
  end

  def self.for_ichain_username(username, attributes)
    user = find_by(username: username)

    raise UserDisabled if user && user.is_disabled

    if user
      user.update_attributes(email: attributes[:email],
                             last_sign_in_at: user.current_sign_in_at,
                             current_sign_in_at: Time.current)
    else
      begin
        user = create!(username: username, email: attributes[:email])
      rescue ActiveRecord::RecordNotUnique
        raise IChainRecordNotFound
      end
    end
    user
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    if login
      where(conditions).where(['lower(username) = :value OR lower(email) = :value', { value: login.downcase }]).first
    else
      where(conditions).first
    end
  end

  # Searches for user based on email. Returns found user or new user.
  # ====Returns
  # * +User::ActiveRecord_Relation+ -> user
  def self.find_for_auth(auth, current_user = nil)
    user = current_user

    if user.nil? # No current user available, user is not already logged in
      user = User.where(email: auth.info.email).first_or_initialize
    end

    if user.new_record?
      user.email = auth.info.email
      user.name = auth.info.name
      user.username = auth.info.username
      user.password = Devise.friendly_token[0, 20]
      user.skip_confirmation!
    end

    user
  end

  # Gets the roles of the user, groups them by role.name and returns the resource(s) of each role
  # ====Returns
  # * +Hash+ * ->  e.g. 'organizer' =>  [conf1, conf2]
  def get_roles
    result = {}
    roles.each do |role|
      resource = Conference.find(role.resource_id).short_title
      if result[role.name].nil?
        result[role.name] = [resource]
      else
        result[role.name] << resource
      end
    end
    result
  end

  def registered
    registrations = self.registrations
    if registrations.count == 0
      'None'
    else
      registrations.map { |r| r.conference.title }.join ', '
    end
  end

  def attended
    registrations_attended = registrations.where(attended: true)
    if registrations_attended.count == 0
      'None'
    else
      registrations_attended.map { |r| r.conference.title }.join ', '
    end
  end

  def confirmed?
    !confirmed_at.nil?
  end

  def proposals(conference)
    events.where('program_id = ? AND event_users.event_role=?', conference.program.id, 'submitter')
  end

  def proposal_count(conference)
    proposals(conference).count
  end

  private

  def setup_role
    if User.count == 1 && User.first.email == 'deleted@localhost.osem'
      self.is_admin = true
    end
  end

  ##
  # Check if biography has an allowed number of words. Used as validation.
  #
  def biography_limit
    if self.biography.present?
      errors.add(:biography, 'is limited to 150 words.') if self.biography.split.length > 150
    end
  end
end

osem-master/app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::BaseController
    load_and_authorize_resource

    def new
      @user = User.new
    end

    def index
      @users = User.all
    end

    def show
      # Variable @show_attributes holds the attributes that are visible for the 'show' action
      # If you want to change the attributes that are shown in the 'show' action of users
      # add/remove the attributes in the following string array
      @show_attributes = %w(name email username nickname affiliation biography registered attended roles created_at
                            updated_at sign_in_count current_sign_in_at last_sign_in_at
                            current_sign_in_ip last_sign_in_ip)
    end

    def update
      message = ''
      if params[:user] && !params[:user][:email].nil?
        if (new_email = params[:user][:email]) != @user.email
          message = " Confirmation email sent to #{new_email}. The new email needs to be confirmed before it can be used."
        end
      end

      if @user.update_attributes(user_params)
        redirect_to admin_users_path, notice: "Updated #{@user.name} (#{@user.email})!" + message
      else
        redirect_to admin_users_path, error: "Could not update #{@user.name} (#{@user.email}). #{@user.errors.full_messages.join('. ')}."
      end
    end

    def edit; end

    private

    def user_params
      params.require(:user).permit(:email, :name, :email_public, :biography, :nickname, :affiliation, :is_admin, :username, :login, :is_disabled,
                                   :tshirt, :mobile, :volunteer_experience, :languages, role_ids: [])
    end
  end
end

osem-master/app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    skip_before_filter :verify_authenticity_token
    skip_authorization_check

    User.omniauth_providers.each do |provider|
      define_method(provider) { handle(provider) }
    end

    private

    def handle(provider)
      auth_hash = request.env['omniauth.auth']
      uid = auth_hash[:uid]
      openid = Openid.find_for_oauth(auth_hash) # Get or create openid
      # If openid exists and is associated with a user, sign in with associated user,
      # even if the email of the associated user and the email of the provided openid are different
      unless (user = openid.user)
        user = User.find_for_auth(auth_hash, current_user) # Get or create users
        user.username = "#{uid}@#{provider}" if user.username.blank?
      end

      begin
        user.save!
        if openid.user != user
          openid.user = user
        end
        openid.save!

        sign_in user
        redirect_to request.env['omniauth.origin'] || root_path,
                    notice: "#{user.email} signed in successfully with #{provider}"
      rescue => e
        flash[:error] = e.message
        redirect_back_or_to new_user_registration_path
      end
    end
  end
end

osem-master/app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  # GET /users/1
  def show
    @events = @user.events.where(state: :confirmed)
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      flash[:error] = "An error prohibited your Profile from being saved: #{@user.errors.full_messages.join('. ')}."
      render :edit
    end
  end

  private

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :biography, :nickname, :affiliation)
    end
end

osem-master/app/views/admin/users/_event_registrations.html.haml
.row
  .col-md-12.page-header
    %h2
      Registrations to Events

  .col-md-12
    .well
      %table.table.table-bordered.table-striped.table-hover.datatable#event_registrations
        %thead
          %th ID
          %th Conference
          %th Title
          %th Attended
        %tbody
          - @user.events_registrations.each do |event_registration|
            - event = event_registration.event
            %tr
              %td= event.id
              %td= link_to event.program.conference.short_title, admin_conference_path(event.program.conference.short_title)
              %td= link_to event.title, admin_conference_program_event_path(event.program.conference.short_title, event)
              %td
                - if @user.attended_event?(event)
                  %i.fa.fa-check.text-success
                - else
                  %i.fa.fa-times.text-danger

osem-master/app/views/admin/users/_form.html.haml
= semantic_form_for [:admin, @user] do |f|
  = f.inputs 'Basic Information' do
    = f.input :is_admin, hint: 'An admin can create a new conference, manage users and make other users admins.'
    = f.input :name, :as => :string
    = f.input :email
    = f.input :affiliation, :as => :string
    = f.input :biography, :input_html => {:rows => 10}
  = f.actions do
    = f.action :submit, :button_html => {:class => "btn btn-primary"}

osem-master/app/views/admin/users/_submissions.html.haml
.row
  .col-md-12.page-header
    %h2
      Submissions (#{@user.events.length}) for #{@user.name}
  .col-md-12
    .well
      %table.table.table-bordered.table-striped.table-hover.datatable#submissions
        %thead
          %th ID
          %th Conference
          %th Title
          %th State
          %th Type
          %th Rating
          %th Created At
        %tbody
          - @user.events.each do |event|
            %tr
              %td= event.id
              %td= link_to event.program.conference.short_title, admin_conference_path(event.program.conference.short_title)
              %td= link_to event.title, admin_conference_program_event_path(event.program.conference.short_title, event)
              %td= event.state
              %td= "#{event.event_type.title} (#{show_time(event.event_type.length)})"
              %td
                - if event.program && event.program.rating && event.program.rating > 0
                  - event.program.rating.times do |counter|
                    - if event.average_rating.to_f.round == counter+1
                      = label_tag 'label_rating', '', class: 'avgrating', avgrate: true
                      = javascript_tag "$('label[avgrate=true]').prevAll().andSelf().addClass('bright');"
                    - else
                      = label_tag 'label_rating', '', class: 'avgrating'
              %td= event.created_at

osem-master/app/views/admin/users/index.html.haml
.row
  .col-md-12
    .page-header
      %h2
        Users
        - if @users
          = "(#{@users.length})"
.row
  .col-md-12.table-responsive
    %table.table.table-striped.table-bordered.table-hover.datatable
      %thead
        %th ID
        %th State
        %th Email
        %th Name
        %th Attended Conferences
        %th Roles
        %th View
        %th Edit
      %tbody
        - @users.each do |user|
          %tr
            %td
              = user.id
            %td
              - if user.confirmed?
                confirmed
              - else
                unconfirmed
            %td
              = user.email
            %td
              = user.name
            %td
              = user.registrations.where(attended: true).count
            %td
              - unless user.get_roles.blank?
                = show_roles(user.get_roles.first(2))
                - if user.get_roles.count > 2
                  = '...'
              - else
                None
            %td
              - if can? :show, user
                = link_to 'View', admin_user_path(user), class: 'btn btn-success'
            %td
              - if can? :update, user
                = link_to 'Edit', edit_admin_user_path(user), class: 'btn btn-primary'

osem-master/app/views/admin/users/show.html.haml
.row
  .col-md-12
    .tabbable
      %ul.nav.nav-tabs
        %li{class: "#{'active' unless params[:tab] == 'submissions-content'}"}
          = link_to 'User Info', '#user-info-content', 'data-toggle'=>'tab'
        - unless @user.events.blank?
          %li{class: "#{'active' if params[:tab] == 'submissions-content'}"}
            = link_to 'Submissions', '#submissions-content', 'data-toggle'=>'tab'
        %li{class: "#{'active' if params[:tab] == 'event_registrations-content'}"}
          = link_to 'Event Registrations', '#event_registrations', 'data-toggle'=>'tab'
      .tab-content
        #user-info-content.tab-pane{class: "#{'active' unless params[:tab] == 'submissions-content'}"}
          - if can? :edit, @user
            .pull-right
              = link_to 'Edit', edit_admin_user_path(@user), class: 'btn btn-primary'
          - if @user.confirmed?
            %span.label.label-success
              confirmed
          - else
            %span.label.label-warning
              unconfirmed
          %table.table
            - @show_attributes.each do |attr|
              %tr
                %td.col-md-2
                  %b
                    = attr.capitalize.gsub('_', ' ')
                - if attr == 'roles'
                  %td
                    = show_roles(@user.get_roles)
                - else
                  %td= @user.send(attr)
        #submissions-content.tab-pane{class: "#{'active' if params[:tab] == 'submissions-content'}"}
          = render 'submissions'
        #event_registrations.tab-pane{class: "#{'active' if params[:tab] == 'event_registrations'}"}
          = render 'event_registrations'