osem-master/config/routes.rb
Osem::Application.routes.draw do

  if ENV['OSEM_ICHAIN_ENABLED'] == 'true'
    devise_for :users, controllers: { registrations: :registrations }
  else
    devise_for :users,
               controllers: {
                   registrations: :registrations, confirmations: :confirmations,
                   omniauth_callbacks: 'users/omniauth_callbacks' },
               path: 'accounts'
  end

  # Use letter_opener_web to open mails in browser (e.g. necessary for Vagrant)
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :users, except: [:new, :index, :create, :destroy]

  namespace :admin do
    resources :users
    resources :comments, only: [:index]
    resources :conference do
      resource :contact, except: [:index, :new, :create, :show, :destroy]
      resource :schedule, only: [:show, :update]
      get 'commercials/render_commercial' => 'commercials#render_commercial'
      resources :commercials, only: [:index, :create, :update, :destroy]
      get '/volunteers_list' => 'volunteers#show'
      get '/volunteers' => 'volunteers#index', as: 'volunteers_info'
      patch '/volunteers' => 'volunteers#update', as: 'volunteers_update'

      resources :registrations, except: [:create, :new] do
        member do
          patch :toggle_attendance

        end
      end

      # Singletons
      resource :splashpage
      resource :venue do
        get 'venue_commercial/render_commercial' => 'venue_commercials#render_commercial'
        resource :venue_commercial, only: [:create, :update, :destroy]
        resources :rooms, except: [:show]
      end
      resource :registration_period
      resource :program do
        resource :cfp
        resources :tracks
        resources :event_types
        resources :difficulty_levels
        resources :events do
          member do
            patch :toggle_attendance
            get :registrations
            post :comment
            patch :accept
            patch :confirm
            patch :cancel
            patch :reject
            patch :unconfirm
            patch :restart
            get :vote
          end
        end
      end

      resources :tickets
      resources :sponsors, except: [:show]
      resources :lodgings, except: [:show]
      resources :targets, except: [:show]
      resources :campaigns, except: [:show]
      resources :emails, only: [:show, :update, :index]
      resources :roles, except: [ :new, :create ] do
        member do
          post :toggle_user
        end
      end

      resources :sponsorship_levels, except: [:show] do
        member do
          patch :up
          patch :down
        end
      end

      resources :questions do
        collection do
          patch :update_conference
        end
      end
    end
  end

  resources :conference, only: [:index, :show] do
    resource :program, only: [] do
      resources :proposal, except: :destroy do
        get 'commercials/render_commercial' => 'commercials#render_commercial'
        resources :commercials, only: [:create, :update, :destroy]
        member do
          get :registrations
          patch '/withdraw' => 'proposal#withdraw'
          get :registrations
          patch '/confirm' => 'proposal#confirm'
          patch '/restart' => 'proposal#restart'
        end
      end
    end

    # TODO: change conference_registrations to singular resource
    resource :conference_registration, path: 'register'
    resources :tickets, only: [:index]
    resources :ticket_purchases, only: [:create, :destroy]
    resource :subscriptions, only: [:create, :destroy]

    member do
      get :schedule
      get :events
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :conferences, only: [ :index, :show ] do
        resources :rooms, only: :index
        resources :tracks, only: :index
        resources :speakers, only: :index
        resources :events, only: :index
      end
      resources :rooms, only: :index
      resources :tracks, only: :index
      resources :speakers, only: :index
      resources :events, only: :index
    end
  end

  get '/admin' => redirect('/admin/conference')

  root to: 'conference#index', via: [:get, :options]
end

osem-master/app/controllers/admin/event_types_controller.rb
module Admin
  class EventTypesController < Admin::BaseController
    load_and_authorize_resource :conference, find_by: :short_title
    load_and_authorize_resource :program, through: :conference, singleton: true
    load_and_authorize_resource :event_type, through: :program

    def index; end

    def edit; end

    def new
      @event_type = @conference.program.event_types.new(color: @conference.next_color_for_collection(:types))
    end

    def create
      @event_type = @conference.program.event_types.new(event_type_params)
      if @event_type.save
        redirect_to admin_conference_program_event_types_path(conference_id: @conference.short_title),
                    notice: 'Event type successfully created.'
      else
        flash[:error] = "Creating event type failed: #{@event_type.errors.full_messages.join('. ')}."
        render :new
      end
    end

    def update
      if @event_type.update_attributes(event_type_params)
        redirect_to admin_conference_program_event_types_path(conference_id: @conference.short_title),
                    notice: 'Event type successfully updated.'
      else
        flash[:error] = "Update event type failed: #{@event_type.errors.full_messages.join('. ')}."
        render :edit
      end
    end

    def destroy
      if @event_type.destroy
        redirect_to admin_conference_program_event_types_path(conference_id: @conference.short_title),
                    notice: 'Event type successfully deleted.'
      else
        redirect_to admin_conference_program_event_types_path(conference_id: @conference.short_title),
                    error: 'Destroying event type failed! '\
                    "#{@event_type.errors.full_messages.join('. ')}."
      end
    end

    private

    def event_type_params
      params.require(:event_type).permit(:title, :length, :minimum_abstract_length, :maximum_abstract_length, :color, :conference_id, :description)
    end
  end
end

osem-master/app/views/admin/event_types/_form.html.haml
.row
  .col-md-12
    .page-header
      %h1
        - if @event_type.new_record?
          New
        Event Type
        = @event_type.title
.row
  .col-md-12
    = semantic_form_for(@event_type, :url => (@event_type.new_record? ? admin_conference_program_event_types_path : admin_conference_program_event_type_path(@conference.short_title, @event_type))) do |f|
      = f.input :title
      = f.input :length, :input_html => {size: 3, type: 'number', step: EventType::LENGTH_STEP, min: EventType::LENGTH_STEP}
      = f.input :description
      = f.input :minimum_abstract_length, :input_html => {:size => 3}
      = f.input :maximum_abstract_length, :input_html => {:size => 3}
      = f.input :color, :input_html => { :size => 6, :type => 'color' }
      %p.text-right
        = f.action :submit, as: :button, button_html: { class: 'btn btn-primary' }

osem-master/app/views/admin/event_types/index.html.haml
.row
  .col-md-12
    .page-header
      %h1 Event Types
      %p.text-muted
        The character of events in your conference
.row
  .col-md-12
    %table.table.table-hover#event_types
      %thead
        %th Title
        %th Description
        %th Length
        %th Abstract Length
        %th Color
        %th Actions
      %tbody
        - @conference.program.event_types.each do |event_type|
          %tr
            %td
              = event_type.title
            %td
              = event_type.description
            %td
              = event_type.length
              Minutes
            %td
              = "#{event_type.minimum_abstract_length} - #{event_type.maximum_abstract_length}"
              Words
            %td
              %span.label{style: "background-color: #{event_type.color}; color: #{ contrast_color(event_type.color) };"}
                = event_type.color
            %td
              .btn-group{role: "group"}
                = link_to 'Edit', edit_admin_conference_program_event_type_path(@conference.short_title, event_type.id),
                method: :get, class: 'btn btn-primary'
                = link_to 'Delete', admin_conference_program_event_type_path(@conference.short_title, event_type.id),
                method: :delete, class: 'btn btn-danger', data: { confirm: "Do you really want to delete #{event_type.name}?" }
.row
  .col-md-12.text-right
    = link_to 'Add Event Type', new_admin_conference_program_event_type_path(@conference.short_title), class: 'btn btn-primary'