osem-master/config/routes.rb
Osem::Application.routes.draw do

  if ENV['OSEM_ICHAIN_ENABLED'] == 'true'
    devise_for :users, controllers: { registrations: :registrations }
  else
    devise_for :users,
               controllers: {
                   registrations: :registrations, confirmations: :confirmations,
                   omniauth_callbacks: 'users/omniauth_callbacks' },
               path: 'accounts'
  end

  # Use letter_opener_web to open mails in browser (e.g. necessary for Vagrant)
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :users, except: [:new, :index, :create, :destroy]

  namespace :admin do
    resources :users
    resources :comments, only: [:index]
    resources :conference do
      resource :contact, except: [:index, :new, :create, :show, :destroy]
      resource :schedule, only: [:show, :update]
      get 'commercials/render_commercial' => 'commercials#render_commercial'
      resources :commercials, only: [:index, :create, :update, :destroy]
      get '/volunteers_list' => 'volunteers#show'
      get '/volunteers' => 'volunteers#index', as: 'volunteers_info'
      patch '/volunteers' => 'volunteers#update', as: 'volunteers_update'

      resources :registrations, except: [:create, :new] do
        member do
          patch :toggle_attendance

        end
      end

      # Singletons
      resource :splashpage
      resource :venue do
        get 'venue_commercial/render_commercial' => 'venue_commercials#render_commercial'
        resource :venue_commercial, only: [:create, :update, :destroy]
        resources :rooms, except: [:show]
      end
      resource :registration_period
      resource :program do
        resource :cfp
        resources :tracks
        resources :event_types
        resources :difficulty_levels
        resources :events do
          member do
            patch :toggle_attendance
            get :registrations
            post :comment
            patch :accept
            patch :confirm
            patch :cancel
            patch :reject
            patch :unconfirm
            patch :restart
            get :vote
          end
        end
      end

      resources :tickets
      resources :sponsors, except: [:show]
      resources :lodgings, except: [:show]
      resources :targets, except: [:show]
      resources :campaigns, except: [:show]
      resources :emails, only: [:show, :update, :index]
      resources :roles, except: [ :new, :create ] do
        member do
          post :toggle_user
        end
      end

      resources :sponsorship_levels, except: [:show] do
        member do
          patch :up
          patch :down
        end
      end

      resources :questions do
        collection do
          patch :update_conference
        end
      end
    end
  end

  resources :conference, only: [:index, :show] do
    resource :program, only: [] do
      resources :proposal, except: :destroy do
        get 'commercials/render_commercial' => 'commercials#render_commercial'
        resources :commercials, only: [:create, :update, :destroy]
        member do
          get :registrations
          patch '/withdraw' => 'proposal#withdraw'
          get :registrations
          patch '/confirm' => 'proposal#confirm'
          patch '/restart' => 'proposal#restart'
        end
      end
    end

    # TODO: change conference_registrations to singular resource
    resource :conference_registration, path: 'register'
    resources :tickets, only: [:index]
    resources :ticket_purchases, only: [:create, :destroy]
    resource :subscriptions, only: [:create, :destroy]

    member do
      get :schedule
      get :events
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :conferences, only: [ :index, :show ] do
        resources :rooms, only: :index
        resources :tracks, only: :index
        resources :speakers, only: :index
        resources :events, only: :index
      end
      resources :rooms, only: :index
      resources :tracks, only: :index
      resources :speakers, only: :index
      resources :events, only: :index
    end
  end

  get '/admin' => redirect('/admin/conference')

  root to: 'conference#index', via: [:get, :options]
end

osem-master/app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :venue
  has_many :events, dependent: :nullify

  before_create :generate_guid

  validates :name, :venue_id, presence: true

  validates :size, numericality: { only_integer: true, greater_than: 0 }, allow_nil: true

  private

  def generate_guid
    guid = SecureRandom.urlsafe_base64
    self.guid = guid
  end
end

osem-master/app/controllers/admin/rooms_controller.rb
module Admin
  class RoomsController < Admin::BaseController
    load_and_authorize_resource :conference, find_by: :short_title
    load_and_authorize_resource :venue, through: :conference, singleton: true
    load_and_authorize_resource through: :venue

    def index; end

    def edit; end

    def new
      @room = @venue.rooms.new
    end

    def create
      @room = @venue.rooms.new(room_params)
      if @room.save
        redirect_to admin_conference_venue_rooms_path(conference_id: @conference.short_title),
                    notice: 'Room successfully created.'
      else
        flash[:error] = "Creating Room failed: #{@room.errors.full_messages.join('. ')}."
        render :new
      end
    end

    def update
      if @room.update_attributes(room_params)
        redirect_to admin_conference_venue_rooms_path(conference_id: @conference.short_title),
                    notice: 'Room successfully updated.'
      else
        flash[:error] = "Update Room failed: #{@room.errors.full_messages.join('. ')}."
        render :edit
      end
    end

    def destroy
      if @room.destroy
        redirect_to admin_conference_venue_rooms_path(conference_id: @conference.short_title),
                    notice: 'Room successfully deleted.'
      else
        redirect_to admin_conference_venue_rooms_path(conference_id: @conference.short_title),
                    error: "Destroying room failed! #{@room.errors.full_messages.join('. ')}."
      end
    end

    private

    def room_params
      params.require(:room).permit(:name, :size)
    end
  end
end

osem-master/app/controllers/api/v1/rooms_controller.rb
module Api
  module V1
    class RoomsController < Api::BaseController
      load_resource :conference, find_by: :short_title
      respond_to :json

      def index
        if @conference
          respond_with @conference.venue ? @conference.venue.rooms : Room.none
        else
          respond_with Room.all
        end
      end
    end
  end
end

osem-master/app/views/admin/rooms/_form.html.haml
.row
  .col-md-12
    .page-header
      %h1
        - if @room.new_record?
          New
        Room
        = @room.name
.row
  .col-md-8
    = semantic_form_for(@room, :url => (@room.new_record? ? admin_conference_venue_rooms_path : admin_conference_venue_room_path(@conference.short_title, @room))) do |f|
      = f.input :name, input_html: { autofocus: true}
      = f.input :size, :input_html => {:size => 5}
      %p.text-right
        = f.action :submit, as: :button, button_html: { class: 'btn btn-primary' }

osem-master/app/views/admin/rooms/index.html.haml
.row
  .col-md-12
    .page-header
      %h1 Rooms
      %p.text-muted
        The rooms of your conference venue

- if @rooms.any?
  .row
    .col-md-12
      %table.table.table-hover#rooms
        %thead
          %th Name
          %th Size
          %th Actions
        %tbody
          - @rooms.each_with_index do |room, index|
            %tr
              %td
                = room.name
              %td
                = room.size
              %td
                = link_to 'Edit', edit_admin_conference_venue_room_path(@conference.short_title, room.id),
                method: :get, class: 'btn btn-primary'
                = link_to 'Delete', admin_conference_venue_room_path(@conference.short_title, room.id),
                method: :delete, class: 'btn btn-danger',
                data: { confirm: "Do you really want to delete #{room.name}? Attention: This room will be removed from all Events that have it set"}
.row
  .col-md-12.text-right
    = link_to 'Add Room', new_admin_conference_venue_room_path(@conference.short_title), class: 'btn btn-primary'